import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import type { StorageProvider, StoredFileRef } from "./types.ts";

// Local-dev-only storage. Files live OUTSIDE the repo's tracked tree
// (gitignored — see .gitignore ".storage/") and are never served
// through any public/unauthenticated URL: the only way to read one
// back is StorageProvider.read(), called from server-side code that
// has already gone through lib/permissions/authContext.ts + RLS.
//
// Paths are isolated by companyId/documentId/versionId so two
// companies (or two versions of the same document) can never collide
// or overwrite each other's files.
const ROOT = process.env.LOCAL_STORAGE_ROOT ?? path.join(process.cwd(), ".storage");

function sanitizeFileName(fileName: string): string {
  const base = path.basename(fileName).replace(/[^a-zA-Z0-9._-]/g, "_");
  return base || "file";
}

export class LocalStorageProvider implements StorageProvider {
  async save(params: {
    companyId: string;
    documentId: string;
    versionId: string;
    fileName: string;
    data: Buffer;
  }): Promise<StoredFileRef> {
    const safeName = sanitizeFileName(params.fileName);
    const relDir = path.join(params.companyId, params.documentId, params.versionId);
    const absDir = path.join(ROOT, relDir);
    await mkdir(absDir, { recursive: true });
    const key = path.join(relDir, safeName).split(path.sep).join("/");
    await writeFile(path.join(ROOT, key), params.data);
    return { key };
  }

  async read(key: string): Promise<Buffer> {
    assertSafeKey(key);
    return readFile(path.join(ROOT, key));
  }

  async remove(key: string): Promise<void> {
    assertSafeKey(key);
    await rm(path.join(ROOT, key), { force: true });
  }
}

// Defense in depth against path traversal even though keys are always
// generated by save() above, never taken verbatim from client input.
function assertSafeKey(key: string): void {
  const normalized = path.normalize(key);
  if (normalized.startsWith("..") || path.isAbsolute(normalized)) {
    throw new Error("storage: rejected unsafe key");
  }
}
